version: 2.1

jobs:
  run-g:
    docker:
      - image: ubuntu:latest

    steps:
      - checkout

      # Install Node.js and npm
      - run:
          name: Install Node.js and npm
          command: |
            apt-get update -y
            apt-get install -y nodejs npm

      # Display Node.js and npm versions
      - run:
          name: Display Node.js version
          command: node -v

      - run:
          name: Display npm version
          command: npm -v

      # Run script.js
      - run:
          name: Run script.js
          command: node script.js

workflows:
  version: 2
  run-g-workflow:
    jobs:
      - run-g
