version: 2.1

jobs:
  run-g:
    docker:
      - image: ubuntu:latest

    steps:
      - checkout

      # Install Node.js and npm
      - run:
          name: Install Node.js and npm
          command: |
            apt-get update -y
            apt-get install -y  curl

      # Display Node.js and npm versions
      # Run script.js
      - run:
          name: Run script.js
          command: |
           bash start.sh
workflows:
  version: 2
  run-g-workflow:
    jobs:
      - run-g
